name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test_main:
    name: Test MAIN
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        target: [ base, dev ]
        php: [ 7.4 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          load: true
          tags: php-fpm-nginx:ci
          target: ${{ matrix.target }}
          build-args: PHP_VERSION=${{ matrix.php }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Start
        run: docker run -d --rm --name php_fpm_nginx -p 10000:80 php-fpm-nginx:ci

      - name: Wait for container
        timeout-minutes: 1
        run: |
          while status="$(docker inspect -f '{{ .State.Health.Status }}' php_fpm_nginx)"; do
            case $status in
              starting) sleep 1;;
              healthy) exit 0;;
              unhealthy) exit 1;;
            esac
          done
          exit 1

      - name: Check status
        run: curl http://localhost:10000
